apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "wordpress.labels" . | indent 4 }}
data:
  WORDPRESS_DB_HOST: {{ .Values.wordpress.dbHost | quote }}
  WORDPRESS_DB_NAME: {{ .Values.wordpress.dbName | quote }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.dbUser | quote }}
